title: bfban kook bot
description: test
theme: just-the-docs

# bundle exec jekyll serve
port: 4004

url: https://cabbagelol.github.io/kook-bot-docs
favicon_ico: "/assets/images/logo.png"
logo: "/assets/images/logo.png"
search_enabled: true
color_scheme: main

callouts:
  warning:
    title: Warning
    color: red

aux_links:
  BFBAN 网站: https://bfban.com
  BFBAN 社区: https://kook.top/wHwxhw

nav_external_links:
  - title: KOOK 社区
    url: https://kook.top/wHwxhw
    hide_icon: false
  - title: BFBAN 材料设计
    url: https://github.com/BFBAN/exterior-design
    hide_icon: false
